[project]
name = "modular-palm-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansys-fluent-core>=0.37.2",
    "inquirer>=3.4.1",
    "readchar>=4.2.1",
    "textual>=7.5.0",
]
